import Head from "next/head";
import { Inter } from "@next/font/google";
// import styles from '@/styles/Home.module.css';
import Search from "@/components/Search";
import FoodList from "@/components/FoodList";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ results }) {
  console.log(results);
  return (
    <>
      <Head>
        <title>Dietary Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-10">
        <h1 className="text-red-500 text-center mb-10">
          This is brand new app using the FDC API
        </h1>

        <Search />

        <h2 className="mb-10">
          Here is the list with the searched foods and their nutrients:
        </h2>

        <FoodList results={results} />

      </main>
    </>
  );
}

export async function getServerSideProps({ query }) {
  console.log("hello from the server");

  const baseUrl = `https://api.nal.usda.gov/fdc/v1/foods/search?query=${query.term}&api_key=${process.env.API_KEY}`;

  const res = await fetch(baseUrl);
  const data = await res.json();
  return {
    props: {
      results: data,
    },
  };
}
